"document"in self&&("classList"in document.createElement("_")&&(!document.createElementNS||"classList"in document.createElementNS("http://www.w3.org/2000/svg","g"))||!function(t){"use strict";if("Element"in t){var e="classList",n="prototype",i=t.Element[n],s=Object,r=String[n].trim||function(){return this.replace(/^\s+|\s+$/g,"")},o=Array[n].indexOf||function(t){for(var e=0,n=this.length;n>e;e++)if(e in this&&this[e]===t)return e;return-1},c=function(t,e){this.name=t,this.code=DOMException[t],this.message=e},a=function(t,e){if(""===e)throw new c("SYNTAX_ERR","The token must not be empty.");if(/\s/.test(e))throw new c("INVALID_CHARACTER_ERR","The token must not contain space characters.");return o.call(t,e)},l=function(t){for(var e=r.call(t.getAttribute("class")||""),n=e?e.split(/\s+/):[],i=0,s=n.length;s>i;i++)this.push(n[i]);this._updateClassName=function(){t.setAttribute("class",this.toString())}},u=l[n]=[],h=function(){return new l(this)};if(c[n]=Error[n],u.item=function(t){return this[t]||null},u.contains=function(t){return~a(this,t+"")},u.add=function(){var t,e=arguments,n=0,i=e.length,s=!1;do t=e[n]+"",~a(this,t)||(this.push(t),s=!0);while(++n<i);s&&this._updateClassName()},u.remove=function(){var t,e,n=arguments,i=0,s=n.length,r=!1;do for(t=n[i]+"",e=a(this,t);~e;)this.splice(e,1),r=!0,e=a(this,t);while(++i<s);r&&this._updateClassName()},u.toggle=function(t,e){var n=this.contains(t),i=n?e!==!0&&"remove":e!==!1&&"add";return i&&this[i](t),e===!0||e===!1?e:!n},u.replace=function(t,e){var n=a(t+"");~n&&(this.splice(n,1,e),this._updateClassName())},u.toString=function(){return this.join(" ")},s.defineProperty){var f={get:h,enumerable:!0,configurable:!0};try{s.defineProperty(i,e,f)}catch(p){void 0!==p.number&&-2146823252!==p.number||(f.enumerable=!1,s.defineProperty(i,e,f))}}else s[n].__defineGetter__&&i.__defineGetter__(e,h)}}(self),function(){"use strict";var t=document.createElement("_");if(t.classList.add("c1","c2"),!t.classList.contains("c2")){var e=function(t){var e=DOMTokenList.prototype[t];DOMTokenList.prototype[t]=function(t){var n,i=arguments.length;for(n=0;i>n;n++)t=arguments[n],e.call(this,t)}};e("add"),e("remove")}if(t.classList.toggle("c3",!1),t.classList.contains("c3")){var n=DOMTokenList.prototype.toggle;DOMTokenList.prototype.toggle=function(t,e){return 1 in arguments&&!this.contains(t)==!e?e:n.call(this,t)}}"replace"in document.createElement("_").classList||(DOMTokenList.prototype.replace=function(t,e){var n=this.toString().split(" "),i=n.indexOf(t+"");~i&&(n=n.slice(i),this.remove.apply(this,n),this.add(e),this.add.apply(this,n.slice(1)))}),t=null}());(function(){if(typeof window.CustomEvent==="function")return false;function CustomEvent(event,params){params=params||{bubbles:false,cancelable:false,detail:undefined};var evt=document.createEvent('CustomEvent');evt.initCustomEvent(event,params.bubbles,params.cancelable,params.detail);return evt;}
CustomEvent.prototype=window.Event.prototype;window.CustomEvent=CustomEvent;})();Element.prototype.remove=function(){this.parentElement.removeChild(this);}
NodeList.prototype.remove=HTMLCollection.prototype.remove=function(){for(var i=this.length-1;i>=0;i--){if(this[i]&&this[i].parentElement){this[i].parentElement.removeChild(this[i]);}}}
var arevt=new CustomEvent('arloadUserActivity');var art_essential_init=function(){window.addEventListener("scroll",function(){const currentScroll=window.pageYOffset;if(currentScroll>20){document.body.classList.add('hnt');}else{document.body.classList.remove('hnt');}});function getScrollbarWidth(){const outer=document.createElement('div');outer.style.visibility='hidden';outer.style.overflow='scroll';outer.style.msOverflowStyle='scrollbar';document.body.appendChild(outer);const inner=document.createElement('div');outer.appendChild(inner);const scrollbarWidth=(outer.offsetWidth-inner.offsetWidth);outer.parentNode.removeChild(outer);return scrollbarWidth;}
var scrollBarWidth=18;scrollBarWidth=getScrollbarWidth();function htmlToElement(html){var div=document.createElement('div');div.innerHTML=html.trim();return div.firstChild;}
function arhide(element){element.classList.add('js-showhidehistory');}
function arshow(element){element.classList.remove('js-showhidehistory');}
if(document.body.clientWidth<615){var cols=document.querySelector('.m_listing-items_container');if(cols!==null){var colsItems=cols.querySelector('.m_listing-items');colsItems.style.display='block';}}
function makeNav(){var menu=document.getElementById('ar_menu');if(menu===null){return false;}
var primaryNav=document.getElementById('ar_menu-primary'),primaryNavItems=primaryNav.querySelectorAll('li'),secondaryNav=document.getElementById('ar_menu-secondary'),secondaryNavItems=secondaryNav.querySelectorAll('li'),navObject=htmlToElement('<ul class="m_nav"></ul>'),menuToggle=htmlToElement('<li><a class="m_nav-control" data-menutype="nav"><span class="m_nav-control-icon">Toggle </span>Menu</a></li>'),menuAdded=false,sideNavObject=htmlToElement('<ul class="m_slideout-menu-page-list" role="nav"></ul>'),tabIndex=2,searchFocus=false,sideNav=document.getElementById('nav');arhide(primaryNav);for(var i=0;i<secondaryNavItems.length;i++){var el=secondaryNavItems[i];tabIndex++;var el_mC=el.querySelector('.m_menu-control');if(el_mC!==null){el_mC.classList.add('m_nav-control');el_mC.classList.remove('m_menu-control');}
var el_icon=el.querySelector('m_menu-control-icon');if(el_icon!=null){el_icon.classList.add('m_nav-control-icon');el_icon.classList.remove('m_menu-control-icon');}
if(el.classList){if(el.className.indexOf('js-search-toggle')&&!menuAdded){navObject.appendChild(menuToggle);}}
navObject.appendChild(el)}
var slideOutBar=document.getElementsByClassName('m_slideout-bar')[0];var slideOut=document.getElementsByClassName('m_slideout')[0];var bodyElement=document.getElementsByTagName("body")[0];var htmlElement=document.getElementsByTagName("html")[0];var headerholder=document.getElementsByClassName('Site-head')[0];slideOutBar.addEventListener('click',function(e){e.stopPropagation();});function closeAndDeactivate(){var allTriggers=document.getElementsByClassName('m_nav-control');var lastActive=null
for(var i=0;i<allTriggers.length;i++){var element=allTriggers.item(i);if(element.className.indexOf('mod--active')>=0){var thisMenuTypePlain=element.getAttribute('data-menutype');var thisMenuType=document.getElementById(thisMenuTypePlain);toggleHideMenu(element,thisMenuType);break;}}}
slideOut.addEventListener('click',function(e){e.preventDefault();closeAndDeactivate();});window.addEventListener('resize',function(e){if(!searchFocus){closeAndDeactivate();}})
var touchMoveFunction=function(e){e.stopPropagation();};function toggleMenu(tr,thisMenuType,thisMenuTypePlain,lastActive){searchFocus=false;if(lastActive!==null){if(lastActive===thisMenuTypePlain){toggleHideMenu(tr,thisMenuType);return true;}}
toggleShowMenu(tr,thisMenuType);}
function toggleShowMenu(tr,thisMenuType){if(thisMenuType!==null){var slideOutSearch=thisMenuType.getElementsByClassName('m_slideout-search');if(slideOutSearch.length>0){searchFocus=true;setTimeout(function(){slideOutSearch[0].focus()},600);}}
if(slideOut.className.indexOf('active')<0){slideOut.classList.remove('fadeOut');slideOut.classList.add('active');slideOut.classList.add('fadeIn');slideOut.classList.add('transition');bodyElement.setAttribute('style',"position:fixed;height:100%;width:100%;");}
tr.classList.add('mod--active');if(thisMenuType!==null){thisMenuType.setAttribute('style',"display:block");}}
function toggleHideMenu(tr,thisMenuType){slideOut.classList.add('fadeOut');setTimeout(function(){slideOut.classList.remove('active');thisMenuType.setAttribute('style',"display:none");tr.classList.remove('mod--active');slideOut.classList.remove('fadeIn');htmlElement.setAttribute('style',"");headerholder.setAttribute('style',"width:100%");bodyElement.setAttribute('style',"position:uset;height:auto;width:100%;");document.body.addEventListener('touchmove',touchMoveFunction);},100);}
sideNavObject.appendChild(htmlToElement('<h4>Navigation</h4>'));for(var i=0;i<primaryNavItems.length;i++){var el=primaryNavItems[i];var el_mC=el.querySelector('.m_menu-control');if(el_mC!==null){el_mC.classList.add('b_submit');el_mC.classList.add('mod--link');el_mC.classList.add('m_full-loader');el_mC.classList.remove('m_menu-control');el_mC.removeAttribute('tab-index');}
sideNavObject.appendChild(el);}
menu.insertBefore(navObject,menu.firstChild);sideNav.insertBefore(sideNavObject,sideNav.firstChild);primaryNav.remove();secondaryNav.remove();menu.classList.remove('m_menu');var menuItemHandler=function(event){var allTriggers=document.getElementsByClassName('m_nav-control');var lastActive=null
for(var i=0;i<allTriggers.length;i++){var element=allTriggers.item(i);if(element.className.indexOf('mod--active')>=0){var thisMenuTypePlain=element.getAttribute('data-menutype');var thisMenuType=document.getElementById(thisMenuTypePlain);thisMenuType.setAttribute('style',"display:none");element.classList.remove('mod--active');lastActive=thisMenuTypePlain;}}
var trigger=event.srcElement;if(trigger.className.indexOf('m_nav-control-icon')>=0||trigger.className.indexOf('m_nav-control')<0){trigger=trigger.parentNode;}
if(trigger.className.indexOf('m_nav-control-icon')>=0||trigger.className.indexOf('m_nav-control')<0){trigger=trigger.parentNode;}
if(!(trigger.className.indexOf('m_nav-override')<0)){return true;}
var thisMenuTypePlain=trigger.getAttribute('data-menutype');var thisMenuType=document.getElementById(thisMenuTypePlain);document.body.removeEventListener('touchmove',touchMoveFunction);toggleMenu(trigger,thisMenuType,thisMenuTypePlain,lastActive);if(thisMenuTypePlain==='social'){document.dispatchEvent(arevt);}
event.preventDefault();}
var allTriggers=document.getElementsByClassName('m_nav-control');for(var i=0;i<allTriggers.length;i++){allTriggers.item(i).addEventListener('click',menuItemHandler);}}
makeNav();}
if(document.readyState==='loading'){document.addEventListener('DOMContentLoaded',function(){art_essential_init();});}else{art_essential_init();}